# Generated by Django 5.1 on 2024-08-13 21:49

import django.core.validators
import supplier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplier_cost_per_kwh'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[supplier.models.validate_cnpj, django.core.validators.RegexValidator('^\\d{14}$', 'CNPJ must be 14 digits.')], verbose_name='CNPJ'),
        ),
    ]
